name: "Define version"
description: "Define the version based on the git tag"
runs:
  using: "composite"
  steps:
    - name: Install semver
      run: npm install -g semver
      shell: bash
    - name: Define the new version
      id: determine_new_version
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        commit_message=$(git log --pretty=format:"%s" HEAD^..HEAD)
        if [[ $commit_message =~ .*!.*: ]]; then
          new_version=$(semver --increment major $latest_tag)
        elif [[ $commit_message =~ ^fix.*: ]]; then
          new_version=$(semver --increment patch $latest_tag)
        elif [[ $commit_message =~ ^feat.*: ]]; then
          new_version=$(semver --increment minor $latest_tag)
        else
          new_version=$latest_tag
        fi
        echo "new_version=$new_version" >> $GITHUB_OUTPUT
      shell: bash
