name: "Check quality"
description: "Check the quality of the Dockerfile"
inputs:
  hadolint_config_file_path:
    description: "where is the hadolint config file to use"
    required: true
  dockerfile_path:
    description: "where is the dockerfile to check"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Hadolint
      run: curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-$(uname -s)-$(uname -m)" && chmod +x hadolint && sudo mv hadolint /usr/local/bin/
      shell: bash
    - name: Run Hadolint
      run: hadolint --config ${{ inputs.hadolint_config_file_path }} ${{ inputs.dockerfile_path }}
      shell: bash
# --config ${{ inputs.hadolint_config_file_path }}
