name: "Publish"
description: "Build and publish the image"
inputs:
  registry_fqdn:
    description: "what is the fqdn of the registry used"
    required: true
    default: ghcr.io
  registry_username:
    description: "what is the username used to login to the registry"
    required: true
  registry_password:
    description: "what is the password used to login to the registry"
    required: true
  image_name:
    description: "what is the name of the image to publish"
    required: true
  image_version:
    description: "what is the version of the image to publish"
    required: true
  context:
    description: "where is the directory with the Dockerfile"
    required: true
    default: "."
  image_build_args:
    description: "add build arg used to build an image"
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry_fqdn }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        tags: |
          ghcr.io/floozy/docker/${{ inputs.image_name }}:${{ inputs.image_version }}
          ghcr.io/floozy/docker/${{ inputs.image_name }}:latest
        build-args: ${{ inputs.image_build_args }}
