name: "Publish"
description: "Build and publish the image"
inputs:
  registry_fqdn:
    description: "what is the fqdn of the registry used"
    required: true
    default: ghcr.io
  registry_repo:
    description: "what is the repository of the registry used"
    required: true
    default: ${{ github.repository }}
  registry_username:
    description: "what is the username used to login to the registry"
    required: true
  registry_password:
    description: "what is the password used to login to the registry"
    required: true
  image_name:
    description: "what is the name of the image to publish"
    required: true
  image_version:
    description: "what is the version of the image to publish"
    required: true
runs:
  using: "composite"
  steps:
    - name: Afficher la variable
      run: |
        # Utilisation de ${{ env.VARIABLE }} pour accéder aux variables d'environnement
        echo "Ma variable : ${{ inputs.registry_repo }}"
      shell: bash
    - name: Login to Github Container Registry
      run: docker login -u ${{ inputs.registry_username }} -p ${{ inputs.registry_password }} ${{ inputs.registry_fqdn }}
      shell: bash
    # - name: Push image
    #   run: docker pull ${{ inputs.registry_repo }}/${{ inputs.registry_username }}/docker/${{ inputs.image_name }}:${{ inputs.image_version }}
    #   shell: bash
