name: Check the quality of the docker image

on:
  workflow_call:
    inputs:
      sparse-checkout:
        required: false
        type: string
      hadolint_config_file_path:
        required: false
        type: string
      cst_config_file_path:
        required: true
        type: string

jobs:
  check_linter:
    name: Check linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.sparse-checkout }}
          sparse-checkout-cone-mode: false
      - name: Check quality
        uses: floozy/github/actions/docker/check-quality@publish-image
        with:
          hadolint_config_file_path: ${{ inputs.hadolint_config_file_path }}

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: check_linter
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.sparse-checkout }}
          sparse-checkout-cone-mode: false
      - name: Build image
        uses: floozy/github/actions/docker/build@publish-image
        with:
          image_name: ${{ github.repository }}
      - name: Run tests
        uses: floozy/github/actions/docker/test@publish-image
        with:
          image_name: ${{ github.repository }}
          cst_config_file_path: ${{ inputs.cst_config_file_path }}
