name: Check the vulnerabilities of the docker image

on:
  workflow_call:
    inputs:
      sparse_checkout:
        required: false
        type: string
        default: Dockerfile
      image_name:
        required: false
        type: string
        default: ${{ github.repository }}
      dockerfile_path:
        required: false
        type: string
        default: "./Dockerfile"
      context:
        required: false
        type: string
        default: "."
      image_build_args:
        required: false
        type: string
      severity:
        required: false
        type: string
        default: low

jobs:
  check_vulnerabilities_in_dockerfile:
    name: Check the vulnerabilities in Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.sparse_checkout }}
          sparse-checkout-cone-mode: false
      - name: Build the image
        uses: floozy/github/actions/docker/build@main
        with:
          image_name: ${{ inputs.image_name }}
          dockerfile_path: ${{ inputs.dockerfile_path }}
          context: ${{ inputs.context }}
          image_build_args: ${{ inputs.image_build_args }}
      - name: Check the vulnerabilities with Grype
        uses: floozy/github/actions/check-vulnerabilities@main
        with:
          data: ${{ github.repository }}
          severity: ${{ inputs.severity }}
