name: Check the quality of the docker image

on:
  workflow_call:
    inputs:
      sparse_checkout:
        required: false
        type: string
        default: |
          Dockerfile
          .hadolint.yaml
          docker-test.yaml
      hadolint_config_file_path:
        required: false
        type: string
      cst_config_file_path:
        required: true
        type: string

jobs:
  check_linter:
    name: Check linter for Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.sparse_checkout }}
          sparse-checkout-cone-mode: false
      - name: Check the quality with Hadolint
        uses: floozy/github/actions/docker/check-quality@main
        with:
          hadolint_config_file_path: ${{ inputs.hadolint_config_file_path }}

  run_tests:
    name: Run tests to validate the docker image
    runs-on: ubuntu-latest
    needs: check_linter
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.sparse-checkout }}
          sparse-checkout-cone-mode: false
      - name: Build the image
        uses: floozy/github/actions/docker/build@main
        with:
          image_name: ${{ github.repository }}
      - name: Run the tests with Container Structure Test
        uses: floozy/github/actions/docker/test@main
        with:
          image_name: ${{ github.repository }}
          cst_config_file_path: ${{ inputs.cst_config_file_path }}
