name: Publish the docker image

on:
  workflow_call:
    inputs:
      sparse_checkout:
        required: false
        type: string
        default: Dockerfile
      image_name:
        required: false
        type: string
        default: ${{ github.repository }}
      registry_username:
        required: false
        type: string
        default: ${{ github.repository_owner }}
    secrets:
      registry_password:
        required: true

jobs:
  publish_docker_image:
    name: Publish the docker image with the correct version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.sparse_checkout }}
          sparse-checkout-cone-mode: false
          fetch-depth: 0
      - name: Define the new version based on SemVer
        id: define_new_version
        uses: floozy/github/actions/git/versionning@main
      - name: Build the image
        if: steps.define_new_version.outputs.version != ''
        uses: floozy/github/actions/docker/build@main
        with:
          image_name: ${{ inputs.image_name }}
      - name: Publish the image
        if: steps.define_new_version.outputs.version != ''
        uses: floozy/github/actions/docker/publish@main
        with:
          registry_username: ${{ github.repository_owner }}
          registry_password: ${{ secrets.registry_password }}
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ steps.define_new_version.outputs.version }}
